### DISCUSSION TITLE
Scout CLI vs Scout Action with package types

### DISCUSSION THREAD

**Discussion by Tsingis** [docker/scout-cli#137] [General]
Wondering if I'm doing something wrong or what causes the difference but let's take `node:20-alpine` image as example from [here](https://github.com/Tsingis/docker-test).

Outcome locally with my machine using CLI:
```
docker pull node:20-alpine
docker scout cves local://node:20-alpine --only-package-type npm
```

![image](https://github.com/user-attachments/assets/28c4c6f1-2fd5-41ea-a0e9-f52b84471bbc)

Outcome with GitHub action scout-action:
```
Run docker/scout-action@v1
  with:
    command: cves,recommendations
    image: local://node:20-alpine
    only-severities: critical,high
    only-package-types: npm
    only-fixed: true
    summary: true
    format: json
    exit-code: true
    github-token: ***
    write-comment: true
```
![image](https://github.com/user-attachments/assets/567c09b3-175e-4d55-93b9-ce27a1503af4)

There's difference in number of packages. Locally CLI seems to actually filter with `--only-package-type npm` where as on Action `only-package-types: npm` just scans all packages (total of 217).
